HOST: "localhost:3000"
HOST_EMAIL: "smtp.mailtrap.io"
MAIL_USER_NAME: "8dd32e576760e8"
MAIL_USER_PASSWORD: "a7bcecdc9eacbf"
MAIL_ADDRESS: "smtp.mailtrap.io"
MAIL_DOMAIN: "smtp.mailtrap.io"
MAIL_PORT: "2525"
